export enum ROLES {
   EXPERT = 'EXPERT',
   AVENGER = 'AVENGER',
   LAWYER = 'LAWYER',
   SAPITOR = 'SAPITOR',
   PARTYMEMBER = 'PARTYMEMBER',
   PARTY = 'PARTY',
   COEXPERT = 'COEXPERT',
   MAGISTRATE = 'MAGISTRATE',
   CLERK = 'CLERK',
   ACCOUNTING = 'ACCOUNTING',
   BUSINESS = 'BUSINESS',
   CUSTOMER_CARE = 'CUSTOMER_CARE',
}
